=== Reset Auto-Increment IDs in Postgres

 ALTER SEQUENCE <table name>_<column name>_seq RESTART WITH <reset id>;

 ALTER SEQUENCE product_id_seq RESTART WITH 1;

== Backup

=== Export

 $ pg_dump [connection-option…] [option…] [dbname]

Example:

 $ pg_dump dangerousdb > /tmp/db.sql
 $ pg_dump -U postgres dvdrental > /tmp/dvdrental-backup.sql

`-U`, username, Connect as the given user +
`-W`, Force a password prompt. This should happen automatically if the server requires password authentication. +
`-F`, format, Selects the format of the output. format can be one of the following:

* p, Output a plain-text SQL script file (default)
* t, Output a tar archive suitable for input into pg_restore. Using this archive format allows reordering and/or exclusion of schema elements at the time the database is restored. It is also possible to limit which data is reloaded at restore time.
* c, Output a custom archive suitable for input into pg_restore. This is the most flexible format in that it allows reordering of data load as well as schema elements. This format is also compressed by default.
