= Suckless Programs Guide =

in this guide we're using *dwm as an example* for installation and configuration.

== dwm installation ==

=== Install necessary packages ===

 # pacman -S xorg-server xorg-xinit xorg-xsetroot

=== `xinitrc` ===

 $ cp /etc/X11/xinit/xinitrc ~/.xinit

*Edit* `.xinitrc`, delete the 5 bottom line and change with `exec dwm`.

=== Install dwm ===

 $ sudo pacman -S wget
 $ wget https://dl.suckless.org/dwm/dwm-6.2.tar.gz
 $ tar -xzvf dwm
 $ cd dwm
 $ sudo make clean install

or 

 $ git clone https://git.suckless.org/dwm
 $ cd dwm
 $ make && sudo make install || sudo make clean install

=== Configuration ===

 $ cd dwm
 $ make clean && rm -f config.h && git reset --hard origin/master
 $ git checkout -b config

Change dwm *configuration* in `config.def.h` file, and keep it in *config branch*.

 $ git add .
 $ git commit -m config
 $ git checkout master
 $ git merge config -m config
 $ make && sudo make install || sudo make clean install

== Patch dwm ==

Download some `patch.diff` file.

 $ cd dwm
 $ make clean && rm -f config.h && git reset --hard origin/master
 $ git checkout -b patch
 $ patch < /path/to/patch.diff

Resolve *conlflict* if there is.

 $ git add .
 $ git commit -m patch
 $ git checkout master
 $ git merge patch -m patch
 $ make && sudo make clean install

== dwmstatus ==

 $ git clone https://git.suckless.org/dwmstatus
 $ cd dwmstatus
 $ make
 $ sudo make PREFIX=/usr clean install

*Add* `dwmstatus 2>&1 >/dev/null &` to your `.xinitrc`.

== xsetroot ==

 while true; do
   SLEEP=30
 
   DATE=$(/usr/bin/date +"%A, %B %d | %H:%M")
 
   BATTERY_STATUS=$(/usr/bin/cat /sys/class/power_supply/BAT0/status)
   BATTERY_CAPACITY=$(/usr/bin/cat /sys/class/power_supply/BAT0/capacity)
   BATTERY="$BATTERY_STATUS $BATTERY_CAPACITY"
 
   MEMORY_TOTAL=$(free -m | awk 'NR%2==0 {print $2}')
   MEMORY_AVAIL=$(free -m | awk 'NR%2==0 {print $7}')
   MEMORY=$(( $MEMORY_TOTAL - $MEMORY_AVAIL ))
 
   xsetroot -name "$MEMORY Mb | $BATTERY % | $DATE | sleep $SLEEP | zqwirp"
   sleep $SLEEP
 done &
